version: "3.8"

services:
  js-crud-client:
    container_name: js-crud-client
    image: js_crud_client_template
    volumes:
      - ./client:/app
    ports:
      - "5173:5173"
  js-crud-server:
    container_name: js-crud-server
    image: js_crud_server_template
    volumes:
      - ./server:/app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=js_crud_database
      - PG_HOST=js-crud-database
    depends_on:
      - js-crud-database
  js-crud-database:
    container_name: js-crud-database
    image: "postgres:14-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=js_crud_database
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: {}
